# Uncomment this line to define a global platform for your project

# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

inhibit_all_warnings!

#MARK: - Common Pods

def pods_base
    platform :ios, '9.0'
    
    pod 'EasyStash'
end


